name: tests

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src
        
    steps:
      - name: Set up Go 1.16
        uses: actions/setup-go@v1
        with:
          go-version: 1.16

      - name: Check out source code
        uses: actions/checkout@v1

      - name: Build
        env:
          GOPROXY: "https://proxy.golang.org"
        run: go build . && go vet .

      - name: Test
        env:
          GOPROXY: "https://proxy.golang.org"
        run: go test -v .
